You have unsaved changes on this file that can be restored.
Kamal-hardware-store-app/.github/workflows
/
main.yml
in
main

Edit

Preview
Indent mode

Spaces
Indent size

2
Line wrap mode

No wrap
Editing main.yml file contents
  1
